# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMResourceDummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=80, unique=True)),
                ('is_started', models.BooleanField(default=False)),
                ('vm_names', models.TextField()),
            ],
        ),
    ]
