# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteapi', '0002_auto_20160118_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmresourcedummy',
            name='vpn_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
