# Generated by Django 4.2 on 2023-05-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteapi', '0003_vmresourcedummy_vpn_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmresourcedummy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
