# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0002_auto_20151103_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='private_key_pem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
