# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenariohelp', '0002_auto_20160122_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='seen_by_author',
            field=models.BooleanField(default=True),
        ),
    ]
