# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from insekta.scenarios.models import Course


default_course = Course.objects.create(short_name='TMP', title='question_course_migration')


def forwards_func(apps, schema_editor):
    Question = apps.get_model('scenariohelp', 'question')
    delete_tmp = True
    for question in Question.objects.all():
        groups = list(question.scenario.groups.all())
        if not groups:
            delete_tmp = False
            continue
        question.course = groups[0].course
        question.save()
    if delete_tmp:
        default_course.delete()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0018_auto_20160222_2237'),
        ('scenariohelp', '0003_question_seen_by_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=default_course.pk, on_delete=django.db.models.deletion.CASCADE, to='scenarios.Course'),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
