# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


default_course_pk = None


def forwards_func_tmp(apps, schema_editor):
    global default_course_pk
    Course = apps.get_model('scenarios', 'Course')
    default_course_pk = Course.objects.create(short_name='TMP', title='question_course_migration')


def forwards_func(apps, schema_editor):
    Question = apps.get_model('scenariohelp', 'Question')
    Course = apps.get_model('scenarios', 'Course')
    delete_tmp = True
    for question in Question.objects.all():
        groups = list(question.scenario.groups.all())
        if not groups:
            delete_tmp = False
            continue
        question.course = groups[0].course
        question.save()
    if delete_tmp:
        Course.objects.get(pk=default_course_pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0018_auto_20160222_2237'),
        ('scenariohelp', '0003_question_seen_by_author'),
    ]

    operations = [
        migrations.RunPython(forwards_func_tmp, migrations.RunPython.noop),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=default_course_pk, on_delete=django.db.models.deletion.CASCADE, to='scenarios.Course'),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
