# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0009_auto_20160124_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariogroup',
            name='scenarios',
        ),
    ]
