# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0011_scenariogroup_scenario_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariogroup',
            name='order_id',
            field=models.IntegerField(default=1),
        ),
    ]
