# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0012_scenariogroup_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariogroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenariogroup',
            name='internal_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
