# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0013_auto_20160125_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariogroup',
            name='frontpage',
            field=models.BooleanField(default=True),
        ),
    ]
