# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0015_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_name',
            field=models.CharField(default='?', max_length=15),
            preserve_default=False,
        ),
    ]
