# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0016_course_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariogroup',
            name='frontpage',
        ),
    ]
