# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 21:37
from __future__ import unicode_literals

from django.db import migrations, models, OperationalError
import django.db.models.deletion

from insekta.scenarios.models import Course

default_course = None

def forward_func(apps, schema_editor):
    global default_course
    Course = apps.get_model('scenarios', 'Course')
    try:
        default_course = Course.objects.all()[0].pk
    except (IndexError, OperationalError):
        default_course = None


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0017_remove_scenariogroup_frontpage'),
    ]

    operations = [
        migrations.RunPython(forward_func, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='course',
            name='scenario_groups',
        ),
        migrations.AddField(
            model_name='scenariogroup',
            name='course',
            field=models.ForeignKey(default=default_course, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_groups', to='scenarios.Course'),
            preserve_default=False,
        ),
    ]
