# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 05:33
from __future__ import unicode_literals

import string

from django.db import migrations, models


key_alpha = string.ascii_lowercase + string.digits + '-'


def prepare_key(key):
    key = ''.join(x for x in key.lower().replace(' ', '-') if x in key_alpha)
    return key if key else 'fixme'


def forwards_func(apps, schema_editor):
    Course = apps.get_model('scenarios', 'Course')
    for course in Course.objects.all():
        base_key = key = prepare_key(course.short_name)
        i = 0
        while Course.objects.filter(key=key).count():
            key = '{}-{}'.format(base_key, i)
            i += 1
        course.key = key
        course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0018_auto_20160222_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='key',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='key',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
