# Generated by Django 2.2.1 on 2019-05-05 15:25

from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    TaskSolve = apps.get_model('scenarios', 'TaskSolve')
    Task = apps.get_model('scenarios', 'Task')
    for task in Task.objects.all():
        for user in task.solved_by.all():
            TaskSolve.objects.create(task=task, user=user)


def reverse_func(apps, schema_editor):
    TaskSolve = apps.get_model('insekta.scenarios', 'TaskSolve')
    TaskSolve.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenarios', '0020_auto_20190505_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='solved_by',
            field=models.ManyToManyField(blank=True, related_name='solved_tasks', through='scenarios.TaskSolve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='solved_by_old',
            field=models.ManyToManyField(blank=True, related_name='solved_tasks_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
