# Generated by Django 2.2.1 on 2019-05-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0021_auto_20190505_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='solved_by_old',
        ),
    ]
