# Generated by Django 2.2.1 on 2019-05-10 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0023_auto_20190510_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskconfiguration',
            name='course_run',
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='course_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scenarios.CourseRun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='tasks',
            field=models.ManyToManyField(through='scenarios.TaskConfiguration', to='scenarios.Task'),
        ),
        migrations.AlterField(
            model_name='taskconfiguration',
            name='task_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scenarios.TaskGroup'),
            preserve_default=False,
        ),
    ]
