# Generated by Django 2.2.1 on 2019-06-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0024_auto_20190510_2351'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskconfiguration',
            unique_together={('task', 'task_group')},
        ),
    ]
